### PR TITLE
fix parsing experiment name from samplesheet

### PR DESCRIPTION
**Pull request by jethror1**
- separate replace for colons from `Experiment Name`

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/dx-streaming-upload/17)

### CODE REVIEW

**Review by JasonLing95 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/dx-streaming-upload/17)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @JasonLing95 and @jethror1)

___
*[`files/notify.py` line 227 at r1](https://reviewable.io/reviews/eastgenomics/dx-streaming-upload/17#-N8NvXpQ8ktuh-r6j9Is:-N8NvXpQ8ktuh-r6j9It:bw17845) ([raw file](https://github.com/eastgenomics/dx-streaming-upload/blob/1457214ec843d0a59af0e637afd6e876d2e99122/files/notify.py#L227)):*
> ```Python
>             experiment_name = [x for x in content if x.startswith('Experiment')]
>             experiment_name = experiment_name[0].replace(
>                 'Experiment Name', '').replace(',', '').replace(
> ```

will it be better to just use regex to remove all symbols 
```
re.sub(r'[^\w]', ' ', sentence)
```



_Code quote:_
```Python
            experiment_name = experiment_name[0].replace(
                'Experiment Name', '').replace(',', '').replace(
                    '\n', '').replace(':', '')
```

**Comment by JasonLing95** [comment]
*[`files/notify.py` line 227 at r1](https://reviewable.io/reviews/eastgenomics/dx-streaming-upload/17#-N8NvXpQ8ktuh-r6j9Is:-N8Nx7vnB-iAZvrEBrd5:b42jn7f) ([raw file](https://github.com/eastgenomics/dx-streaming-upload/blob/1457214ec843d0a59af0e637afd6e876d2e99122/files/notify.py#L227)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

will it be better to just use regex to remove all symbols 
```
re.sub(r'[^\w]', ' ', sentence)
```
</blockquote></details>

`re.sub(r'[^\w]', ' ', experiment_name[0])`

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/dx-streaming-upload/17)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @JasonLing95)

___
*[`files/notify.py` line 227 at r1](https://reviewable.io/reviews/eastgenomics/dx-streaming-upload/17#-N8NvXpQ8ktuh-r6j9Is:-N8O46xY32Sk1SWr0nLn:bjzzx1w) ([raw file](https://github.com/eastgenomics/dx-streaming-upload/blob/1457214ec843d0a59af0e637afd6e876d2e99122/files/notify.py#L227)):*
realised since this is a csv it makes more sense to just split:

```
>>> s="Experiment Name,MYE0070,,,,,"
>>> s.split(',')[1]
'MYE0070'
```

**Review by JasonLing95 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/dx-streaming-upload/17)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jethror1)

**Pull request merged**
