### PR TITLE
BINFRA2 - Dockerising and slackifying dx-streaming-upload

### PR DESCRIPTION
**Pull request by jethror1**
## Summary
- Pull in latest changes from dnanexus:master
  - bug fixes, switched to Python3, correctly works with NovaSeqs

## Changes
- added Docker image
  - sets up `dx-upload` user and required directories
- docker test script (`docker_test.sh`)
  - small test script to simulate a sequencing run, writes some random data to initiate an upload and send notifcations (configured playbook in `docker-tests/test_files/`)
- added Slack notifications in `notify.py`
  - supports sending to 2 channels (one for general logs, one for fail alerts)
- added checking of partial sequenced runs on incomplete cycle dirs
  - handled in `notify.py` (`checkCycles()`)
  - tested with `docker_test.sh` script generating a run dir with mismatch in expected run in `RunInfo.xml` and run directory, will prevent downstream analysis being triggered
- Changes to ansible role in `tasks/main.yml`
  - add use of `sequencer-id` field to roles, allows for uniquely named lock files by sequencer to concurrently upload runs from 2 or more sequencers (see `docker-tests/test_files/test-playbook-template.yml`)

## Fixes
- #2 
- #3 
- #4 

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/dx-streaming-upload/6)

### CODE REVIEW

**Review by JasonLing95 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 9 files at r2, 1 of 3 files at r4, 3 of 8 files at r6, 2 of 2 files at r7, 2 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/dx-streaming-upload/6)* status: 9 of 14 files reviewed, 7 unresolved discussions (waiting on @jethror1 and @mattgarner)

___
*[`Dockerfile` line 26 at r4](https://reviewable.io/reviews/eastgenomics/dx-streaming-upload/6#-N3KtC3QEA-gcQ_LRAsY:-N3KtC3QEA-gcQ_LRAsZ:b-om08n) ([raw file](https://github.com/eastgenomics/dx-streaming-upload/blob/4bd329d4f2b18fc8ffd57ff78e2f762799ab1746/Dockerfile#L26)):*
> ```Dockerfile
> RUN sed -i '3s%^%#%' /home/dx-upload/dx-streaming-upload/tasks/main.yml
> RUN sed -i '4s%^%#%' /home/dx-upload/dx-streaming-upload/tasks/main.yml
> RUN sed -i '5s%^%#%' /home/dx-upload/dx-streaming-upload/tasks/main.yml
> ```

RUN sed -i '3,5s%^%#%' /home/dx-upload/dx-streaming-upload/tasks/main.yml



_Code quote:_
```Dockerfile
RUN sed -i '3s%^%#%' /home/dx-upload/dx-streaming-upload/tasks/main.yml
RUN sed -i '4s%^%#%' /home/dx-upload/dx-streaming-upload/tasks/main.yml
RUN sed -i '5s%^%#%' /home/dx-upload/dx-streaming-upload/tasks/main.yml
```
___
*[`files/incremental_upload.py` line 405 at r8](https://reviewable.io/reviews/eastgenomics/dx-streaming-upload/6#-N3LqhOB0pOe67DuFTvj:-N3LqhOB0pOe67DuFTvk:b-wsfmcp) ([raw file](https://github.com/eastgenomics/dx-streaming-upload/blob/46d83e1266e4d8ffa73b08ed992f610d96a9dec8/files/incremental_upload.py#L405)):*
> ```Python
>     # open and close to create file in case its the first time
>     notify_log = f"{args.sequencer_id}.start_notify.log".strip('"\'')
>     open(notify_log, 'a').close()
> ```

the with clause below will automatically make a file and handle the closure. This line may not be required.



_Code quote:_
```Python
open(notify_log, 'a').close()
```
___
*[`files/notify.py` line 15 at r8](https://reviewable.io/reviews/eastgenomics/dx-streaming-upload/6#-N3LseGo8uNpwm6g-r6o:-N3LseGo8uNpwm6g-r6p:b-46gk1m) ([raw file](https://github.com/eastgenomics/dx-streaming-upload/blob/46d83e1266e4d8ffa73b08ed992f610d96a9dec8/files/notify.py#L15)):*
> ```Python
> from urllib3.util import Retry
> 
> from bs4 import BeautifulSoup as bs
> ```

bs4 package is not in requirements.txt



_Code quote:_
```Python
bs4 import BeautifulSoup as bs
```
___
*[`files/notify.py` line 18 at r8](https://reviewable.io/reviews/eastgenomics/dx-streaming-upload/6#-N3LsXye1IOfOsGFs4ee:-N3LsXye1IOfOsGFs4ef:b-h573x1) ([raw file](https://github.com/eastgenomics/dx-streaming-upload/blob/46d83e1266e4d8ffa73b08ed992f610d96a9dec8/files/notify.py#L18)):*
> ```Python
> 
> 
> class slack():
> ```

Felt like class should be capitalized



_Code quote:_
```Python
slack()
```
___
*[`files/notify.py` line 74 at r8](https://reviewable.io/reviews/eastgenomics/dx-streaming-upload/6#-N3Lt-2t-ZY15RviNgt6:-N3Lt-2t-ZY15RviNgt7:b-jho16s) ([raw file](https://github.com/eastgenomics/dx-streaming-upload/blob/46d83e1266e4d8ffa73b08ed992f610d96a9dec8/files/notify.py#L74)):*
> ```Python
>         response = http.post(
>             'https://slack.com/api/chat.postMessage', {
>                 'token': self.slack_token,
> ```

Slack post request often return JSON with key "ok" and value True or False to denote whether the message is sent successfully or not. You might want to have a check response['ok'] to catch Slack API error to differentiate from the request.Session error which point more towards our server internet issue



_Code quote:_
```Python
        response = http.post(
            'https://slack.com/api/chat.postMessage', {
                'token': self.slack_token,
                'channel': f"#{channel}",
                'text': message
            }).json()
```
___
*[`files/notify.py` line 80 at r8](https://reviewable.io/reviews/eastgenomics/dx-streaming-upload/6#-N3Lu8sKCmh5mC-smJt6:-N3Lu8sKCmh5mC-smJt7:bd3jiuo) ([raw file](https://github.com/eastgenomics/dx-streaming-upload/blob/46d83e1266e4d8ffa73b08ed992f610d96a9dec8/files/notify.py#L80)):*
> ```Python
> 
> 
> class checkCycles():
> ```

CheckCycles



_Code quote:_
```Python
checkCycles()
```
___
*[`files/notify.py` line 107 at r8](https://reviewable.io/reviews/eastgenomics/dx-streaming-upload/6#-N3LyZOW0JG1TpZ2OLJw:-N3LyZOW0JG1TpZ2OLJx:bpt6dmk) ([raw file](https://github.com/eastgenomics/dx-streaming-upload/blob/46d83e1266e4d8ffa73b08ed992f610d96a9dec8/files/notify.py#L107)):*
> ```Python
>             ])
>             message = (
>                 f"Total sequencing cycles do not appear to have completed.\n"
> ```

which is the actual message or is it the combination of both



_Code quote:_
```Python
            message = f"\n\t".join([
                f"\t\t\t\t{x}\t:\t{y}" for x, y in zip(lanes, max_cycles)
            ])
            message = (
                f"Total sequencing cycles do not appear to have completed.\n"
                f"Expected cycles: *{cycle_count}*\n\n"
                f"Cycles found:\n\n"
                f"\t\t\t\t\tLane\t\tCycles\n\n\t{message}"
            )
```

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/dx-streaming-upload/6)* status: 9 of 14 files reviewed, 7 unresolved discussions (waiting on @JasonLing95 and @mattgarner)

___
*[`Dockerfile` line 26 at r4](https://reviewable.io/reviews/eastgenomics/dx-streaming-upload/6#-N3KtC3QEA-gcQ_LRAsY:-N3PoMLz0BHdCJXlDs6b:b-896fix) ([raw file](https://github.com/eastgenomics/dx-streaming-upload/blob/4bd329d4f2b18fc8ffd57ff78e2f762799ab1746/Dockerfile#L26)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

RUN sed -i '3,5s%^%#%' /home/dx-upload/dx-streaming-upload/tasks/main.yml
</blockquote></details>

Done.
___
*[`files/incremental_upload.py` line 405 at r8](https://reviewable.io/reviews/eastgenomics/dx-streaming-upload/6#-N3LqhOB0pOe67DuFTvj:-N3PojNLDYXB4A7y0Lzt:b-896fix) ([raw file](https://github.com/eastgenomics/dx-streaming-upload/blob/46d83e1266e4d8ffa73b08ed992f610d96a9dec8/files/incremental_upload.py#L405)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

the with clause below will automatically make a file and handle the closure. This line may not be required.
</blockquote></details>

Done.
___
*[`files/notify.py` line 15 at r8](https://reviewable.io/reviews/eastgenomics/dx-streaming-upload/6#-N3LseGo8uNpwm6g-r6o:-N3Pp0teAGMuzQmYohya:b-896fix) ([raw file](https://github.com/eastgenomics/dx-streaming-upload/blob/46d83e1266e4d8ffa73b08ed992f610d96a9dec8/files/notify.py#L15)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

bs4 package is not in requirements.txt
</blockquote></details>

Done.
___
*[`files/notify.py` line 18 at r8](https://reviewable.io/reviews/eastgenomics/dx-streaming-upload/6#-N3LsXye1IOfOsGFs4ee:-N3PpEX18pg1cwp5ZxgV:bxq51pp) ([raw file](https://github.com/eastgenomics/dx-streaming-upload/blob/46d83e1266e4d8ffa73b08ed992f610d96a9dec8/files/notify.py#L18)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

Felt like class should be capitalized
</blockquote></details>

naming isn't enforced so I like to stick with camelcase and lower case for the first, there's some libraries that do this and others that capitalize the first so :shrug:

also now can't be bothered renaming them all 
___
*[`files/notify.py` line 74 at r8](https://reviewable.io/reviews/eastgenomics/dx-streaming-upload/6#-N3Lt-2t-ZY15RviNgt6:-N3PrG4g8BOp4dIHt6Y0:b-896fix) ([raw file](https://github.com/eastgenomics/dx-streaming-upload/blob/46d83e1266e4d8ffa73b08ed992f610d96a9dec8/files/notify.py#L74)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

Slack post request often return JSON with key "ok" and value True or False to denote whether the message is sent successfully or not. You might want to have a check response['ok'] to catch Slack API error to differentiate from the request.Session error which point more towards our server internet issue
</blockquote></details>

Done.
___
*[`files/notify.py` line 80 at r8](https://reviewable.io/reviews/eastgenomics/dx-streaming-upload/6#-N3Lu8sKCmh5mC-smJt6:-N3PrH5g1_2nVoJMYvZi:b-elpusk) ([raw file](https://github.com/eastgenomics/dx-streaming-upload/blob/46d83e1266e4d8ffa73b08ed992f610d96a9dec8/files/notify.py#L80)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

CheckCycles
</blockquote></details>

see above, sticking with camelcase and lowercase for first
___
*[`files/notify.py` line 107 at r8](https://reviewable.io/reviews/eastgenomics/dx-streaming-upload/6#-N3LyZOW0JG1TpZ2OLJw:-N3PrdAx1-sFVo4kSQr0:b-fe3hkl) ([raw file](https://github.com/eastgenomics/dx-streaming-upload/blob/46d83e1266e4d8ffa73b08ed992f610d96a9dec8/files/notify.py#L107)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

which is the actual message or is it the combination of both
</blockquote></details>

yeah it combines it, the first is just to format it properly, see this for an example: https://binfx.slack.com/archives/G01DKUVQZ96/p1653915205397389

**Review by JasonLing95 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1, 1 of 9 files at r2, 1 of 8 files at r6, 5 of 6 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/dx-streaming-upload/6)* status: 14 of 15 files reviewed, 1 unresolved discussion (waiting on @jethror1 and @mattgarner)

___
*[`files/incremental_upload.py` line 418 at r9](https://reviewable.io/reviews/eastgenomics/dx-streaming-upload/6#-N4UCx1i-8_6iLU_KH4X:-N4UCx1i-8_6iLU_KH4Y:bu9je7g) ([raw file](https://github.com/eastgenomics/dx-streaming-upload/blob/088a516e6df6e7c437e79744b4f392d03435558b/files/incremental_upload.py#L418)):*
> ```Python
>                 message=(
>                     f":upload-cloud: dx-streaming-upload: starting upload of "
>                     f"run *{run_id}*\n\t\t{usage}"
> ```

slack class itself 



_Code quote:_
```Python
        try:
            slack().send(
                message=(
                    f":upload-cloud: dx-streaming-upload: starting upload of "
                    f"run *{run_id}*\n\t\t{usage}"
                ), run=run_id, log=True
            )
        except Exception as e:
            print_stderr(f"Error sending slack message: {e}")
```

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/dx-streaming-upload/6)* status: 14 of 15 files reviewed, all discussions resolved (waiting on @mattgarner)

___
*[`files/incremental_upload.py` line 418 at r9](https://reviewable.io/reviews/eastgenomics/dx-streaming-upload/6#-N4UCx1i-8_6iLU_KH4X:-N4UIAuA0AWxoqHp0KP4:b414ypr) ([raw file](https://github.com/eastgenomics/dx-streaming-upload/blob/088a516e6df6e7c437e79744b4f392d03435558b/files/incremental_upload.py#L418)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

slack class itself 
</blockquote></details>

what do you mean? I only call the `send()` function twice per run (on starting and completing or an error), so just initialise the class at the same time as calling `send()` to have it in one line (initialising the class only sets class attributes from env variables [here](https://github.com/eastgenomics/dx-streaming-upload/blob/088a516e6df6e7c437e79744b4f392d03435558b/files/notify.py#L22 )

**Review by JasonLing95 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/dx-streaming-upload/6)* status: 14 of 15 files reviewed, all discussions resolved (waiting on @mattgarner)

___
*[`files/incremental_upload.py` line 418 at r9](https://reviewable.io/reviews/eastgenomics/dx-streaming-upload/6#-N4UCx1i-8_6iLU_KH4X:-N4UNPFICoeqmcq5FeLn:b-zee7l1) ([raw file](https://github.com/eastgenomics/dx-streaming-upload/blob/088a516e6df6e7c437e79744b4f392d03435558b/files/incremental_upload.py#L418)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

what do you mean? I only call the `send()` function twice per run (on starting and completing or an error), so just initialise the class at the same time as calling `send()` to have it in one line (initialising the class only sets class attributes from env variables [here](https://github.com/eastgenomics/dx-streaming-upload/blob/088a516e6df6e7c437e79744b4f392d03435558b/files/notify.py#L22 )
</blockquote></details>

my bad. mistype and forgot to delete before publish

**Review by JasonLing95 — APPROVED** [review]
> Reviewed 4 of 4 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/dx-streaming-upload/6)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mattgarner)

**Review by JasonLing95 — APPROVED** [review]
> Reviewed 5 of 5 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/dx-streaming-upload/6)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mattgarner)

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 2 of 9 files at r2, 3 of 8 files at r6, 1 of 2 files at r7, 1 of 6 files at r9, 5 of 5 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/dx-streaming-upload/6)* status: all files reviewed, 1 unresolved discussion (waiting on @jethror1)

___
*[`files/incremental_upload.py` line 525 at r12](https://reviewable.io/reviews/eastgenomics/dx-streaming-upload/6#-N4lHAPODObONZI0w7uW:-N4lHAPODObONZI0w7uX:b-cu0y8t) ([raw file](https://github.com/eastgenomics/dx-streaming-upload/blob/2a09edc346f8d98ffe72ca3d6dba2e51190c7e1e/files/incremental_upload.py#L525)):*
> ```Python
>             local_sample_sheet = 'SampleSheet.csv'
>         else:
>             if len(files) > 1:
> ```

Would it be better to use neither in this case? 
If 2 samplesheets are present then perhaps someone has dropped the sheet from another run into this one. Arbitrarily selecting one of the two could lead to trouble.



_Code quote:_
```Python
            if len(files) > 1:
                print_stderr(
                    f"More than one samplesheet match found: {files}.\n"
                    "Selecting first and continuing..."
```

**Review by mattgarner — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/dx-streaming-upload/6)* status: all files reviewed, 3 unresolved discussions (waiting on @jethror1)

___
*[`files/notify.py` line 18 at r12](https://reviewable.io/reviews/eastgenomics/dx-streaming-upload/6#-N4lIjCX5mfT1yxaW-fM:-N4lIjCX5mfT1yxaW-fN:biw31g) ([raw file](https://github.com/eastgenomics/dx-streaming-upload/blob/2a09edc346f8d98ffe72ca3d6dba2e51190c7e1e/files/notify.py#L18)):*
> ```Python
> 
> 
> class slack():
> ```

`Slack`

https://peps.python.org/pep-0008/#class-names



_Code quote:_
```Python
slack
```
___
*[`files/notify.py` line 91 at r12](https://reviewable.io/reviews/eastgenomics/dx-streaming-upload/6#-N4lJE4zAtIKYqSqQ9QU:-N4lJE4zAtIKYqSqQ9QV:b-wg78tq) ([raw file](https://github.com/eastgenomics/dx-streaming-upload/blob/2a09edc346f8d98ffe72ca3d6dba2e51190c7e1e/files/notify.py#L91)):*
> ```Python
> 
> 
> class checkCycles():
> ```

and this one



_Code quote:_
```Python
c
```

**Review by mattgarner — COMMENTED** [review]
> Reviewed 1 of 6 files at r1, 1 of 9 files at r2, 1 of 6 files at r9.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/dx-streaming-upload/6)* status: all files reviewed, 3 unresolved discussions (waiting on @jethror1)

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/dx-streaming-upload/6)* status: 10 of 15 files reviewed, 3 unresolved discussions (waiting on @JasonLing95 and @mattgarner)

___
*[`files/notify.py` line 18 at r12](https://reviewable.io/reviews/eastgenomics/dx-streaming-upload/6#-N4lIjCX5mfT1yxaW-fM:-N4mTyc39FGNUD1EQ346:b-896fix) ([raw file](https://github.com/eastgenomics/dx-streaming-upload/blob/2a09edc346f8d98ffe72ca3d6dba2e51190c7e1e/files/notify.py#L18)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

`Slack`

https://peps.python.org/pep-0008/#class-names
</blockquote></details>

Done.
___
*[`files/notify.py` line 91 at r12](https://reviewable.io/reviews/eastgenomics/dx-streaming-upload/6#-N4lJE4zAtIKYqSqQ9QU:-N4mTzKJ5EdEMOzAKzv1:b-896fix) ([raw file](https://github.com/eastgenomics/dx-streaming-upload/blob/2a09edc346f8d98ffe72ca3d6dba2e51190c7e1e/files/notify.py#L91)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

and this one
</blockquote></details>

Done.

**Pull request merged**
